version: '3.8'

services:
  postgres-db:
    image: "postgres:13-alpine"
    container_name: postgres-container
    expose:
      - 5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my_db

    volumes:


      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql
      -  my_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - my-network
  python-app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-app-container

    depends_on:
      - postgres-db
    stdin_open: true
    tty: true
    command: sh

    networks:
      - my-network


networks:
  my-network:
    driver: bridge
volumes:
  my_volume:
